learn_templates/learn_templates/urls.py
from django.contrib import admin
from django.urls import path
from templates_app import views
from django.urls import include, re_path


urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('templates/',include('templates_app.urls')),
]

learn_templates/templates_app/urls.py
from templates_app import views
from django.urls import path, re_path, include

# TEMPLATE TAGGING: Django will automatically look for this variable
# 'app_name', which we set as the actual app_name.
# This allows us to use the template tagging...

app_name = 'templates_app'

urlpatterns = [
    # 'relative' link...
    re_path(r'^relative/$', views.relative, name='relative'),
    # 'other' link...
    re_path(r'other/$', views.other, name='other'),
]

# Here we are defnining the URL paths for the different html pages
# within our tamplates_app. We tell the URL which view to point to!

# See relative_url_templates.html for detail on relative URLs execution!

learn_templates/templates_app/models.py
from django.db import models

# Create your models here.

learn_templates/templates_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request, 'templates_app/index.html',context=context_dict)

def other(request):
    return render(request, 'templates_app/other.html')

def relative(request):
    return render(request, 'templates_app/relative_url_templates.html')

learn_templates/templates/templates_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'templates_app:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this block will be inhertied when we extend -->
      {% endblock %}
    </div>

  </body>
</html>

learn_templates/templates/templates_app/index.html
<!DOCTYPE html>
{% extends "templates_app/base.html" %}
  {% block body_block %}
  {% load my_extras %}
    <h1>Welcome To Index</h1>
    <h2>This is the index.html page on top of base.html</h2>
    <!-- Random context variables... -->
    <h1>{{ text|cutter:'hello' }}</h1>
    <br>
    <h1>{{ number|add:"99" }}</h1>
{% endblock %}

learn_templates/templates/templates_app/other.html
<!DOCTYPE html>
{% extends "templates_app/base.html" %}
  {% block body_block %}
    <h1>Welcome To Other</h1>
    <h2>This is an example of template inheritance</h2>
  {% endblock %}

learn_templates/templates/templates_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome To Relative URL Templates</h1>
    <p>Here we are demonstrating how a relative URL template looks: </p>
    <a href="{% url 'templates_app:other' %}">THE OTHER PAGE</a>
    <br>
    <a href="{% url 'admin:index' %}">LINK TO ADMIN PAGE</a>
    <br>
    <a href="{% url 'index' %}">TO BASE INDEX PAGE</a>
  </body>
</html>